:identifier:
  :root: 2.16.840.1.113883.3.15
  :extension: header_ext
:authors:
- :ids:
  - :root: 2.16.840.1.113883.3.416
    :extension: health-data-standards-gem
  :device:
    :name: popHealth - Intermountain Healthcare (nmedw branch)
    :model: GitHub commit = fbffd122b7
  :addresses:
  - :street:
    - Intermountain Healthcare
    - 5121 S Cottonwood St.
    :city: Murray
    :state: UT
    :zip: '84157'
    :country: US
  :telecoms:
  - :use: WP
    :value: (801)507-7000
  :organization:
    :ids:
    - :root: 2.16.840.1.113883.3.15
      :extension: 
    :name: Intermountain Healthcare
:custodian:
  :ids:
  - :root: 2.16.840.1.113883.3.15
    :extension: custodian_ext
  :person:
    :given: Teresa
    :family: Hall
  :organization:
    :ids:
    - :root: 2.16.840.1.113883.3.15
      :extension: custodian_organization_ext
    :name: 'Intermountain Healthcare'
:legal_authenticator:
  :ids:
  - :root: 2.16.840.1.113883.3.15
    :extension: legal_authenticator_ext
  :addresses: []
  :telecoms: []
  :time: 
  :person:
    :given: Teresa
    :family: Hall
  :organization:
    :ids:
    - :root: 2.16.840.1.113883.3.15
      :extension: legal_authenticator_org_ext
    :name: 'Intermountain Healthcare'
